descriptors = {
        "earlier_diagnosis___1": "Varasem - Südamepuudulikkus",
        "earlier_diagnosis___2": "Varasem - KOK/Astma",
        "earlier_diagnosis___3": "Pole ei SP ega KOK/Astmat",
        "uhdisk_diag___1": "Pneumoonia",
        "uhdisk_diag___2": "Kopsupais/kopsuturse",
        "uhdisk_diag___3": "Müokardi infarkt",
        "uhdisk_diag___4": "Kopsuarteri trombemboolia",
        "uhdisk_diag___5": "UHDISK - KOK/astma",
        "uhdisk_diag___6": "Pleuraefusioon",
        "uhdisk_diag___7": "Pneumotooraks",
        "uhdisk_diag___8": "Perikardi efusioon",
        "non_uhdisk_diag___1": "Kõhuvalu",
        "non_uhdisk_diag___2": "Alaseljavalu",
        "non_uhdisk_diag___3": "Rindkerevalu k.a. ülaseljavalu",
        "non_uhdisk_diag___4": "Peavalu",
        "non_uhdisk_diag___5": "Kuseteede infektsioon",
        "non_uhdisk_diag___6": "Kõhuõõne põletikuline haigus",
        "non_uhdisk_diag___7": "Pehme koe infektsioon",
        "non_uhdisk_diag___8": "Muu koldega infektsioon",
        "non_uhdisk_diag___9": "Kodade virvendus või laperdus",
        "non_uhdisk_diag___10": "Muud rütmihäired",
        "non_uhdisk_diag___11": "Ajuinfarkt/TIA",
        "non_uhdisk_diag___12": "Vertiigo",
        "non_uhdisk_diag___13": "Sünkoop",
        "non_uhdisk_diag___14": "Epilepsia",
        "non_uhdisk_diag___15": "Kõrge vererõhk",
        "non_uhdisk_diag___16": "Alkoholi kuritarvitamine",
        "non_uhdisk_diag___17": "Ülemiste hingamisteede infektsioon",
        "non_uhdisk_diag___18": "Allergilised reaktsioonid",
        "non_uhdisk_diag___19": "Iiveldus/oksendamine",
        "non_uhdisk_diag___20": "Muud kaebused",
        "non_uhdisk_diag___21": "Seedetrakti verejooks",
        "non_uhdisk_diag___22": "Kuseteede kivi",
        "non_uhdisk_diag___23": "Günekoloogiline probleem",
        "non_uhdisk_diag___24": "Pöördumised protseduuriks"
        }


